/**
 * @file config.js
 * @module config
 * @description Centralised configuration loader for the TotalAgility Teams Bot.
 *
 * All runtime settings are read from environment variables so that sensitive
 * values (API keys, connection strings) stay out of source control.
 *
 * Environment variables are populated by:
 * - `.localConfigs` / `.localConfigs.testTool`  — generated by the Teams Toolkit
 *   YAML deploy steps from the `env/.env.*` files.
 * - Azure App Service app-settings — injected by the Bicep template at
 *   `infra/azure.bicep` during `teamsapp provision`.
 *
 * @see {@link https://aka.ms/teamsfx-v5.0-guide} Teams Toolkit project guide
 */

const config = {
  // ── Bot Framework identity ──────────────────────────────────────────────
  /** @type {string} Microsoft Entra (AAD) application (client) ID for the bot. */
  MicrosoftAppId: process.env.BOT_ID,

  /** @type {string} Bot authentication type — "MultiTenant" locally, "UserAssignedMsi" on Azure. */
  MicrosoftAppType: process.env.BOT_TYPE,

  /** @type {string} Microsoft Entra tenant ID. */
  MicrosoftAppTenantId: process.env.BOT_TENANT_ID,

  /** @type {string} Microsoft Entra client secret (only used for MultiTenant local dev). */
  MicrosoftAppPassword: process.env.BOT_PASSWORD,

  // ── TotalAgility connection ─────────────────────────────────────────────
  /** @type {string} Base URL of the TotalAgility REST/OpenAPI endpoint (e.g. `https://tenant.dev.kofaxcloud.com/services/sdk/v1`). */
  totalAgilityEndpoint: process.env.TOTALAGILITY_ENDPOINT,

  /** @type {string} API key used to authenticate calls to TotalAgility. */
  totalAgilityApiKey: process.env.TOTALAGILITY_API_KEY,

  /** @type {string} Process name of the TotalAgility Agent to invoke. */
  totalAgilityAgentName: process.env.TOTALAGILITY_AGENT_NAME,

  /** @type {string} Process ID (GUID) of the TotalAgility Agent. */
  totalAgilityAgentId: process.env.TOTALAGILITY_AGENT_ID,

  /** @type {string} Email/username for test-mode SSO login into TotalAgility. */
  totalAgilityTestUserName: process.env.TOTALAGILITY_TEST_USERNAME,

  /** @type {string} When `"true"`, forces SSO login as `totalAgilityTestUserName` instead of the real Teams user. */
  totalAgilityUseTestUser: process.env.TOTALAGILITY_USE_TEST_USER,

  // ── Optional LLM tuning parameters (strings — defaults applied in code) ─
  /** @type {string|undefined} LLM temperature override. Default: `1`. */
  totalAgilityTemperature: process.env.TOTALAGILITY_TEMPERATURE,

  /** @type {string|undefined} Whether to use a fixed seed for LLM responses. Default: `"true"`. */
  totalAgilityUseSeed: process.env.TOTALAGILITY_USE_SEED,

  /** @type {string|undefined} Fixed seed value for deterministic LLM output. Default: `27535`. */
  totalAgilitySeed: process.env.TOTALAGILITY_SEED,

  // ── Conversation history ────────────────────────────────────────────────
  /** @type {string|undefined} Max messages to keep in the rolling conversation history. Default: `10`. */
  conversationHistoryMaxEntries: process.env.CONVERSATION_HISTORY_MAX_ENTRIES,

  // ── Proactive notifications ─────────────────────────────────────────────
  /** @type {string|undefined} Static bearer token that 3rd-party callers must present to use `/api/notifications`. */
  notificationsBearerToken: process.env.NOTIFICATIONS_BEARER_TOKEN,

  /** @type {string|undefined} Azure Storage connection string for persisting conversation references. Falls back to in-memory when absent. */
  azureStorageConnectionString: process.env.AZURE_STORAGE_CONNECTION_STRING,
};

module.exports = config;
